{"@t":"2020-03-13T11:09:46.9286804Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Booting Umbraco 8.5.4.","TimingId":"3c03c20","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":11532,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"5032458a-ee55-4ead-925e-7cee08b8e0ac"}
{"@t":"2020-03-13T11:09:46.9476635Z","@mt":"Booting site '{HostingSiteName}', app '{HostingApplicationID}', path '{HostingPhysicalPath}', server '{MachineName}'.","HostingSiteName":"Aarhus-Web-Dev-Coop","HostingApplicationID":"/LM/W3SVC/2/ROOT","HostingPhysicalPath":"E:\\school\\2nd sem\\CMS\\Mandatory\\Aarhus-Web-Dev-Coop\\","MachineName":"MO-PC","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":11532,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"5032458a-ee55-4ead-925e-7cee08b8e0ac"}
{"@t":"2020-03-13T11:09:47.0296473Z","@mt":"Acquiring.","SourceContext":"Umbraco.Core.MainDom","ProcessId":11532,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"5032458a-ee55-4ead-925e-7cee08b8e0ac"}
{"@t":"2020-03-13T11:09:47.0306367Z","@mt":"Acquired.","SourceContext":"Umbraco.Core.MainDom","ProcessId":11532,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"5032458a-ee55-4ead-925e-7cee08b8e0ac"}
{"@t":"2020-03-13T11:10:09.2311811Z","@mt":"{FailMessage} ({Duration}ms) [Timing {TimingId}]","@l":"Error","@x":"Umbraco.Core.Exceptions.BootFailedException: A connection string is configured but Umbraco could not connect to the database.\r\n   at Umbraco.Core.RuntimeState.DetermineRuntimeLevel(IUmbracoDatabaseFactory databaseFactory, ILogger logger) in D:\\a\\1\\s\\src\\Umbraco.Core\\RuntimeState.cs:line 194\r\n   at Umbraco.Core.Runtime.CoreRuntime.DetermineRuntimeLevel(IUmbracoDatabaseFactory databaseFactory, IProfilingLogger profilingLogger) in D:\\a\\1\\s\\src\\Umbraco.Core\\Runtime\\CoreRuntime.cs:line 259\r\n   at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer) in D:\\a\\1\\s\\src\\Umbraco.Core\\Runtime\\CoreRuntime.cs:line 146","FailMessage":"Boot failed.","Duration":22309,"TimingId":"3c03c20","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":11532,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR","HttpRequestNumber":1,"HttpRequestId":"5032458a-ee55-4ead-925e-7cee08b8e0ac"}
{"@t":"2020-03-13T11:10:19.3148928Z","@mt":"Stopping ({SignalSource})","SignalSource":"environment","SourceContext":"Umbraco.Core.MainDom","ProcessId":11532,"ProcessName":"iisexpress","ThreadId":18,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:10:19.3179048Z","@mt":"Released ({SignalSource})","SignalSource":"environment","SourceContext":"Umbraco.Core.MainDom","ProcessId":11532,"ProcessName":"iisexpress","ThreadId":18,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:10:47.2247390Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Booting Umbraco 8.5.4.","TimingId":"76bd9a9","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":11532,"ProcessName":"iisexpress","ThreadId":6,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"5246c84d-c47b-4baf-8931-e9b631d76f75"}
{"@t":"2020-03-13T11:10:47.2327367Z","@mt":"Booting site '{HostingSiteName}', app '{HostingApplicationID}', path '{HostingPhysicalPath}', server '{MachineName}'.","HostingSiteName":"Aarhus-Web-Dev-Coop","HostingApplicationID":"/LM/W3SVC/2/ROOT","HostingPhysicalPath":"E:\\school\\2nd sem\\CMS\\Mandatory\\Aarhus-Web-Dev-Coop\\","MachineName":"MO-PC","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":11532,"ProcessName":"iisexpress","ThreadId":6,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"5246c84d-c47b-4baf-8931-e9b631d76f75"}
{"@t":"2020-03-13T11:10:47.2837209Z","@mt":"Acquiring.","SourceContext":"Umbraco.Core.MainDom","ProcessId":11532,"ProcessName":"iisexpress","ThreadId":6,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"5246c84d-c47b-4baf-8931-e9b631d76f75"}
{"@t":"2020-03-13T11:10:47.2847194Z","@mt":"Acquired.","SourceContext":"Umbraco.Core.MainDom","ProcessId":11532,"ProcessName":"iisexpress","ThreadId":6,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"5246c84d-c47b-4baf-8931-e9b631d76f75"}
{"@t":"2020-03-13T11:11:05.8930681Z","@mt":"{FailMessage} ({Duration}ms) [Timing {TimingId}]","@l":"Error","@x":"Umbraco.Core.Exceptions.BootFailedException: A connection string is configured but Umbraco could not connect to the database.\r\n   at Umbraco.Core.RuntimeState.DetermineRuntimeLevel(IUmbracoDatabaseFactory databaseFactory, ILogger logger) in D:\\a\\1\\s\\src\\Umbraco.Core\\RuntimeState.cs:line 194\r\n   at Umbraco.Core.Runtime.CoreRuntime.DetermineRuntimeLevel(IUmbracoDatabaseFactory databaseFactory, IProfilingLogger profilingLogger) in D:\\a\\1\\s\\src\\Umbraco.Core\\Runtime\\CoreRuntime.cs:line 259\r\n   at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer) in D:\\a\\1\\s\\src\\Umbraco.Core\\Runtime\\CoreRuntime.cs:line 146","FailMessage":"Boot failed.","Duration":18675,"TimingId":"76bd9a9","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":11532,"ProcessName":"iisexpress","ThreadId":6,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR","HttpRequestNumber":1,"HttpRequestId":"5246c84d-c47b-4baf-8931-e9b631d76f75"}
{"@t":"2020-03-13T11:11:15.9308542Z","@mt":"Stopping ({SignalSource})","SignalSource":"environment","SourceContext":"Umbraco.Core.MainDom","ProcessId":11532,"ProcessName":"iisexpress","ThreadId":12,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:11:15.9308542Z","@mt":"Released ({SignalSource})","SignalSource":"environment","SourceContext":"Umbraco.Core.MainDom","ProcessId":11532,"ProcessName":"iisexpress","ThreadId":12,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:11:41.8351746Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Booting Umbraco 8.5.4.","TimingId":"c5213f5","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":11532,"ProcessName":"iisexpress","ThreadId":6,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"74043365-2fa0-4fb1-ad8f-0edaf2369ded"}
{"@t":"2020-03-13T11:11:41.8441717Z","@mt":"Booting site '{HostingSiteName}', app '{HostingApplicationID}', path '{HostingPhysicalPath}', server '{MachineName}'.","HostingSiteName":"Aarhus-Web-Dev-Coop","HostingApplicationID":"/LM/W3SVC/2/ROOT","HostingPhysicalPath":"E:\\school\\2nd sem\\CMS\\Mandatory\\Aarhus-Web-Dev-Coop\\","MachineName":"MO-PC","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":11532,"ProcessName":"iisexpress","ThreadId":6,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"74043365-2fa0-4fb1-ad8f-0edaf2369ded"}
{"@t":"2020-03-13T11:11:41.8901676Z","@mt":"Acquiring.","SourceContext":"Umbraco.Core.MainDom","ProcessId":11532,"ProcessName":"iisexpress","ThreadId":6,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"74043365-2fa0-4fb1-ad8f-0edaf2369ded"}
{"@t":"2020-03-13T11:11:41.8911667Z","@mt":"Acquired.","SourceContext":"Umbraco.Core.MainDom","ProcessId":11532,"ProcessName":"iisexpress","ThreadId":6,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"74043365-2fa0-4fb1-ad8f-0edaf2369ded"}
{"@t":"2020-03-13T11:12:00.4999502Z","@mt":"{FailMessage} ({Duration}ms) [Timing {TimingId}]","@l":"Error","@x":"Umbraco.Core.Exceptions.BootFailedException: A connection string is configured but Umbraco could not connect to the database.\r\n   at Umbraco.Core.RuntimeState.DetermineRuntimeLevel(IUmbracoDatabaseFactory databaseFactory, ILogger logger) in D:\\a\\1\\s\\src\\Umbraco.Core\\RuntimeState.cs:line 194\r\n   at Umbraco.Core.Runtime.CoreRuntime.DetermineRuntimeLevel(IUmbracoDatabaseFactory databaseFactory, IProfilingLogger profilingLogger) in D:\\a\\1\\s\\src\\Umbraco.Core\\Runtime\\CoreRuntime.cs:line 259\r\n   at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer) in D:\\a\\1\\s\\src\\Umbraco.Core\\Runtime\\CoreRuntime.cs:line 146","FailMessage":"Boot failed.","Duration":18671,"TimingId":"c5213f5","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":11532,"ProcessName":"iisexpress","ThreadId":6,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR","HttpRequestNumber":1,"HttpRequestId":"74043365-2fa0-4fb1-ad8f-0edaf2369ded"}
{"@t":"2020-03-13T11:12:10.5256481Z","@mt":"Stopping ({SignalSource})","SignalSource":"environment","SourceContext":"Umbraco.Core.MainDom","ProcessId":11532,"ProcessName":"iisexpress","ThreadId":22,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:12:10.5256481Z","@mt":"Released ({SignalSource})","SignalSource":"environment","SourceContext":"Umbraco.Core.MainDom","ProcessId":11532,"ProcessName":"iisexpress","ThreadId":22,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:18:48.6310939Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Booting Umbraco 8.5.4.","TimingId":"d7a4f8a","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bcd75a6a-e132-4c98-b0a2-90ef3b625e25"}
{"@t":"2020-03-13T11:18:48.6550861Z","@mt":"Booting site '{HostingSiteName}', app '{HostingApplicationID}', path '{HostingPhysicalPath}', server '{MachineName}'.","HostingSiteName":"Aarhus-Web-Dev-Coop","HostingApplicationID":"/LM/W3SVC/2/ROOT","HostingPhysicalPath":"E:\\school\\2nd sem\\CMS\\Mandatory\\Aarhus-Web-Dev-Coop\\","MachineName":"MO-PC","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bcd75a6a-e132-4c98-b0a2-90ef3b625e25"}
{"@t":"2020-03-13T11:18:48.7370604Z","@mt":"Acquiring.","SourceContext":"Umbraco.Core.MainDom","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bcd75a6a-e132-4c98-b0a2-90ef3b625e25"}
{"@t":"2020-03-13T11:18:48.7390574Z","@mt":"Acquired.","SourceContext":"Umbraco.Core.MainDom","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bcd75a6a-e132-4c98-b0a2-90ef3b625e25"}
{"@t":"2020-03-13T11:18:50.2693779Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Resolving composer types.","TimingId":"545c1a5","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bcd75a6a-e132-4c98-b0a2-90ef3b625e25"}
{"@t":"2020-03-13T11:18:51.0131822Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Resolved.","Duration":742,"TimingId":"545c1a5","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bcd75a6a-e132-4c98-b0a2-90ef3b625e25"}
{"@t":"2020-03-13T11:18:51.4961225Z","@mt":"Registered with MainDom, localContentDbExists? {LocalContentDbExists}, localMediaDbExists? {LocalMediaDbExists}","LocalContentDbExists":true,"LocalMediaDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bcd75a6a-e132-4c98-b0a2-90ef3b625e25"}
{"@t":"2020-03-13T11:18:51.4961225Z","@mt":"Creating the content store, localContentDbExists? {LocalContentDbExists}","LocalContentDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bcd75a6a-e132-4c98-b0a2-90ef3b625e25"}
{"@t":"2020-03-13T11:18:51.4981222Z","@mt":"Creating the media store, localMediaDbExists? {LocalMediaDbExists}","LocalMediaDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bcd75a6a-e132-4c98-b0a2-90ef3b625e25"}
{"@t":"2020-03-13T11:18:52.4740097Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Loading content from local cache file","TimingId":"4a9a65a","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bcd75a6a-e132-4c98-b0a2-90ef3b625e25"}
{"@t":"2020-03-13T11:18:52.4960028Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":22,"TimingId":"4a9a65a","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bcd75a6a-e132-4c98-b0a2-90ef3b625e25"}
{"@t":"2020-03-13T11:18:52.5050006Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Loading media from local cache file","TimingId":"fd5ea9b","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bcd75a6a-e132-4c98-b0a2-90ef3b625e25"}
{"@t":"2020-03-13T11:18:52.5060003Z","@mt":"Tried to load media from the local cache file but it was empty.","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bcd75a6a-e132-4c98-b0a2-90ef3b625e25"}
{"@t":"2020-03-13T11:18:52.5060003Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":0,"TimingId":"fd5ea9b","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bcd75a6a-e132-4c98-b0a2-90ef3b625e25"}
{"@t":"2020-03-13T11:18:52.5060003Z","@mt":"Loading media from local db raised warnings, will reload from database.","@l":"Warning","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"WARN ","HttpRequestNumber":1,"HttpRequestId":"bcd75a6a-e132-4c98-b0a2-90ef3b625e25"}
{"@t":"2020-03-13T11:18:52.5100105Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Loading media from database","TimingId":"1bf4010","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bcd75a6a-e132-4c98-b0a2-90ef3b625e25"}
{"@t":"2020-03-13T11:18:52.8221987Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":311,"TimingId":"1bf4010","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bcd75a6a-e132-4c98-b0a2-90ef3b625e25"}
{"@t":"2020-03-13T11:18:52.8841801Z","@mt":"Profiler is VoidProfiler, not profiling (must run debug mode to profile).","SourceContext":"Umbraco.Web.Logging.WebProfilerComponent","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bcd75a6a-e132-4c98-b0a2-90ef3b625e25"}
{"@t":"2020-03-13T11:18:53.0131371Z","@mt":"Initializing Umbraco internal event handlers for cache refreshing.","SourceContext":"Umbraco.Web.Cache.DistributedCacheBinderComponent","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bcd75a6a-e132-4c98-b0a2-90ef3b625e25"}
{"@t":"2020-03-13T11:18:53.0571421Z","@mt":"Adding examine event handlers for {RegisteredIndexers} index providers.","RegisteredIndexers":3,"SourceContext":"Umbraco.Web.Search.ExamineComponent","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bcd75a6a-e132-4c98-b0a2-90ef3b625e25"}
{"@t":"2020-03-13T11:18:53.1300776Z","@mt":"Starting initialize async background thread.","SourceContext":"Umbraco.Web.Search.BackgroundIndexRebuilder","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bcd75a6a-e132-4c98-b0a2-90ef3b625e25"}
{"@t":"2020-03-13T11:18:53.1310610Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Booted.","Duration":4509,"TimingId":"d7a4f8a","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"bcd75a6a-e132-4c98-b0a2-90ef3b625e25"}
{"@t":"2020-03-13T11:18:53.5910722Z","@mt":"New url {Url} detected, re-discovering application url.","Url":"http://localhost/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":13,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"357e77fd-89ab-410e-b5cb-bff2736492c1"}
{"@t":"2020-03-13T11:18:53.5920702Z","@mt":"ApplicationUrl: {UmbracoAppUrl} (UmbracoModule request)","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":13,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"357e77fd-89ab-410e-b5cb-bff2736492c1"}
{"@t":"2020-03-13T11:22:09.8182938Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T11:22:21.8252151Z","@mt":"Scheduled health check results:","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Folder & File Permissions","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Folder & File Permissions","HealthCheckResult":"Success","HealthCheckMessage":"All folders have the correct permissions set.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Folder & File Permissions","HealthCheckResult":"Success","HealthCheckMessage":"All files have the correct permissions set.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"SMTP Settings","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"WARN "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"SMTP Settings","HealthCheckResult":"Error","HealthCheckMessage":"In the Web.config file system.net/mailsettings section, the host is not configured.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Macro errors","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"WARN "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Macro errors","HealthCheckResult":"Error","HealthCheckMessage":"MacroErrors are set to 'throw' which will prevent some or all pages in your site from loading completely if there are any errors in macros. Rectifying this will set the value to 'inline'.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Notification Email Settings","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"WARN "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Notification Email Settings","HealthCheckResult":"Error","HealthCheckMessage":"Notification email is still set to the default value of <strong>your@email.here</strong>.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Try Skip IIS Custom Errors","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Try Skip IIS Custom Errors","HealthCheckResult":"Success","HealthCheckMessage":"Try Skip IIS Custom Errors is set to 'true' and you're using IIS version '10.0'.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Custom Errors","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Custom Errors","HealthCheckResult":"Success","HealthCheckMessage":"Custom errors are set to 'RemoteOnly'.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Trace Mode","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Trace Mode","HealthCheckResult":"Success","HealthCheckMessage":"Trace mode is disabled.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Debug Compilation Mode","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Debug Compilation Mode","HealthCheckResult":"Success","HealthCheckMessage":"Debug compilation mode is disabled.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Cross-site scripting Protection (X-XSS-Protection header)","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"WARN "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Cross-site scripting Protection (X-XSS-Protection header)","HealthCheckResult":"Error","HealthCheckMessage":"Error pinging the URL http://localhost/umbraco - 'Unable to connect to the remote server'","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Cookie hijacking and protocol downgrade attacks Protection (Strict-Transport-Security Header (HSTS))","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"WARN "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Cookie hijacking and protocol downgrade attacks Protection (Strict-Transport-Security Header (HSTS))","HealthCheckResult":"Error","HealthCheckMessage":"Error pinging the URL http://localhost/umbraco - 'Unable to connect to the remote server'","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Content/MIME Sniffing Protection","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"WARN "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Content/MIME Sniffing Protection","HealthCheckResult":"Error","HealthCheckMessage":"Error pinging the URL http://localhost/umbraco - 'Unable to connect to the remote server'","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Excessive Headers","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"WARN "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Excessive Headers","HealthCheckResult":"Warning","HealthCheckMessage":"[httpsCheckInvalidUrl]","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Click-Jacking Protection","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"WARN "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Click-Jacking Protection","HealthCheckResult":"Error","HealthCheckMessage":"Error pinging the URL http://localhost/umbraco - 'Unable to connect to the remote server'","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"HTTPS Configuration","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"WARN "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"HTTPS Configuration","HealthCheckResult":"Error","HealthCheckMessage":"You are currently not viewing the site using the HTTPS scheme.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"HTTPS Configuration","HealthCheckResult":"Info","HealthCheckMessage":"The appSetting 'Umbraco.Core.UseHttps' is set to 'false' in your web.config file. Once you access this site using the HTTPS scheme, that should be set to 'true'.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:22:21.8262148Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"HTTPS Configuration","HealthCheckResult":"Error","HealthCheckMessage":"Error pinging the URL https://localhost/umbraco - 'Unable to connect to the remote server'","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T11:27:11.8309551Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":34,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T11:32:13.8462899Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":45,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T11:37:15.8606624Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":63,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T11:42:17.8768849Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":68,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T11:47:19.8914959Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":31,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T11:52:21.9085302Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":26,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T11:57:23.9266927Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":29,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T12:02:25.9426878Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":62,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T12:07:27.9558096Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":51,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T12:12:29.9707012Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":55,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T12:17:31.9859801Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":20,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T12:22:34.0138369Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":32,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T12:27:36.0194157Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":19,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T12:32:38.0249096Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":21,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T12:37:40.0411616Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":11,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T12:42:42.0566669Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":94,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T12:47:44.0650593Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":31,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T12:52:46.0755220Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":21,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T12:57:48.0812678Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":19,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T13:02:50.1000052Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":25,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T13:07:52.1174939Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":23,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T13:12:54.1310162Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":62,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T13:17:56.1465271Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":29,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T13:22:58.1571425Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":77,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T13:28:00.1608157Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":65,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T13:33:02.1733796Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":75,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T13:38:04.1919440Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":66,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T13:43:06.2117256Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":51,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T13:48:08.2237936Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":112,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T13:53:10.2289297Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":99,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T13:58:12.2460465Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":138,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T14:03:14.2523681Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":131,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T14:08:16.2594700Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":102,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T14:13:18.2704712Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":96,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T14:18:20.2825708Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":186,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T14:23:22.2976627Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":185,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T14:28:24.3129996Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":149,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T14:33:26.3171064Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":61,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T14:38:28.3309549Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":188,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T14:43:30.3503720Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":154,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T14:48:32.3636087Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":127,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T14:53:34.3762276Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":155,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T14:58:36.3941344Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":65,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T15:03:38.4102755Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":130,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T15:08:40.4244032Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":127,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T15:13:42.4388612Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":137,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T15:17:40.5509839Z","@mt":"{LogPrefix} Terminating {Immediate}","LogPrefix":"[RebuildIndexesOnStartup] ","Immediate":"","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":129,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.5509839Z","@mt":"{LogPrefix} Waiting for tasks to complete","LogPrefix":"[RebuildIndexesOnStartup] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":129,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.5526138Z","@mt":"{LogPrefix} Tasks {TaskStatus}, terminated","LogPrefix":"[RebuildIndexesOnStartup] ","TaskStatus":"completed","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":129,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.5526138Z","@mt":"{LogPrefix} Terminating {Immediate}","LogPrefix":"[ScheduledPublishing] ","Immediate":"","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":129,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.5526138Z","@mt":"{LogPrefix} Waiting for tasks to complete","LogPrefix":"[ScheduledPublishing] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":129,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.5529813Z","@mt":"{LogPrefix} Tasks {TaskStatus}, terminated","LogPrefix":"[ScheduledPublishing] ","TaskStatus":"completed","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":52,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.5529813Z","@mt":"{LogPrefix} Terminating {Immediate}","LogPrefix":"[ScheduledTasks] ","Immediate":"","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":129,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.5529813Z","@mt":"{LogPrefix} Waiting for tasks to complete","LogPrefix":"[ScheduledTasks] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":129,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.5529813Z","@mt":"{LogPrefix} Tasks {TaskStatus}, terminated","LogPrefix":"[ScheduledTasks] ","TaskStatus":"completed","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":129,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.5529813Z","@mt":"{LogPrefix} Terminating {Immediate}","LogPrefix":"[HealthCheckNotifier] ","Immediate":"","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":129,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.5529813Z","@mt":"{LogPrefix} Waiting for tasks to complete","LogPrefix":"[HealthCheckNotifier] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":129,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.5529813Z","@mt":"{LogPrefix} Terminating {Immediate}","LogPrefix":"[LogScrubber] ","Immediate":"","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":129,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.5529813Z","@mt":"{LogPrefix} Waiting for tasks to complete","LogPrefix":"[LogScrubber] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":129,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.5529813Z","@mt":"Stopping ({SignalSource})","SignalSource":"environment","SourceContext":"Umbraco.Core.MainDom","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":129,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.5529813Z","@mt":"{LogPrefix} Tasks {TaskStatus}, terminated","LogPrefix":"[HealthCheckNotifier] ","TaskStatus":"completed","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":194,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.5529813Z","@mt":"{LogPrefix} Tasks {TaskStatus}, terminated","LogPrefix":"[LogScrubber] ","TaskStatus":"completed","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":61,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.6199493Z","@mt":"Released from MainDom","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":129,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.6199493Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Examine shutting down","TimingId":"a7f6f27","SourceContext":"Umbraco.Web.Search.ExamineComponent","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":129,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.6249499Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":4,"TimingId":"a7f6f27","SourceContext":"Umbraco.Web.Search.ExamineComponent","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":129,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.6249499Z","@mt":"Released ({SignalSource})","SignalSource":"environment","SourceContext":"Umbraco.Core.MainDom","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":129,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.6249499Z","@mt":"{LogPrefix} Terminating {Immediate}","LogPrefix":"[KeepAlive] ","Immediate":"","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":129,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.6249499Z","@mt":"{LogPrefix} Waiting for tasks to complete","LogPrefix":"[KeepAlive] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":129,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.6249499Z","@mt":"{LogPrefix} Tasks {TaskStatus}, terminated","LogPrefix":"[KeepAlive] ","TaskStatus":"completed","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":194,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.6289487Z","@mt":"{LogPrefix} Terminating {Immediate}","LogPrefix":"[TempFileCleanup] ","Immediate":"","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":129,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.6289487Z","@mt":"{LogPrefix} Waiting for tasks to complete","LogPrefix":"[TempFileCleanup] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":129,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.6289487Z","@mt":"{LogPrefix} Terminating {Immediate}","LogPrefix":"[ServerInstProcess] ","Immediate":"","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":129,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.6289487Z","@mt":"{LogPrefix} Waiting for tasks to complete","LogPrefix":"[ServerInstProcess] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":129,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.6289487Z","@mt":"{LogPrefix} Terminating {Immediate}","LogPrefix":"[ServerRegistration] ","Immediate":"","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":129,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.6289487Z","@mt":"{LogPrefix} Waiting for tasks to complete","LogPrefix":"[ServerRegistration] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":129,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.6289487Z","@mt":"{LogPrefix} Tasks {TaskStatus}, terminated","LogPrefix":"[TempFileCleanup] ","TaskStatus":"completed","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":52,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.6289487Z","@mt":"{LogPrefix} Tasks {TaskStatus}, terminated","LogPrefix":"[ServerInstProcess] ","TaskStatus":"completed","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.6289487Z","@mt":"{LogPrefix} Tasks {TaskStatus}, terminated","LogPrefix":"[ServerRegistration] ","TaskStatus":"completed","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":189,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:40.6379570Z","@mt":"Application shutdown. Details: {ShutdownReason}\r\n\r\n_shutDownMessage={ShutdownMessage}\r\n\r\n_shutDownStack={ShutdownStack}","ShutdownReason":"MaxRecompilationsReached","ShutdownMessage":"Recompilation limit of 50 reached\r\nHostingEnvironment initiated shutdown\r\nHostingEnvironment caused shutdown","ShutdownStack":"   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)\r\n   at System.Environment.get_StackTrace()\r\n   at System.Web.Hosting.HostingEnvironment.InitiateShutdownInternal()\r\n   at System.Web.Hosting.HostingEnvironment.InitiateShutdownWithoutDemand()\r\n   at System.Web.HttpRuntime.ShutdownAppDomain(String stackTrace)\r\n   at System.Web.Compilation.DiskBuildResultCache.ShutdownCallBack(Object state)\r\n   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()\r\n   at System.Threading.ThreadPoolWorkQueue.Dispatch()\r\n   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()","SourceContext":"Umbraco.Web.UmbracoApplicationBase","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":129,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:17:46.7125420Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Booting Umbraco 8.5.4.","TimingId":"02f7f27","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":195,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"12d52710-f77d-4a10-8dde-05169b235959"}
{"@t":"2020-03-13T15:17:46.7210693Z","@mt":"Booting site '{HostingSiteName}', app '{HostingApplicationID}', path '{HostingPhysicalPath}', server '{MachineName}'.","HostingSiteName":"Aarhus-Web-Dev-Coop","HostingApplicationID":"/LM/W3SVC/2/ROOT","HostingPhysicalPath":"E:\\school\\2nd sem\\CMS\\Mandatory\\Aarhus-Web-Dev-Coop\\","MachineName":"MO-PC","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":195,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"12d52710-f77d-4a10-8dde-05169b235959"}
{"@t":"2020-03-13T15:17:46.7550590Z","@mt":"Acquiring.","SourceContext":"Umbraco.Core.MainDom","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":195,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"12d52710-f77d-4a10-8dde-05169b235959"}
{"@t":"2020-03-13T15:17:46.7550590Z","@mt":"Acquired.","SourceContext":"Umbraco.Core.MainDom","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":195,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"12d52710-f77d-4a10-8dde-05169b235959"}
{"@t":"2020-03-13T15:17:46.8740332Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Resolving composer types.","TimingId":"c057533","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":195,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"12d52710-f77d-4a10-8dde-05169b235959"}
{"@t":"2020-03-13T15:17:46.9545112Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Resolved.","Duration":80,"TimingId":"c057533","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":195,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"12d52710-f77d-4a10-8dde-05169b235959"}
{"@t":"2020-03-13T15:17:47.7447640Z","@mt":"Registered with MainDom, localContentDbExists? {LocalContentDbExists}, localMediaDbExists? {LocalMediaDbExists}","LocalContentDbExists":true,"LocalMediaDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":195,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"12d52710-f77d-4a10-8dde-05169b235959"}
{"@t":"2020-03-13T15:17:47.7447640Z","@mt":"Creating the content store, localContentDbExists? {LocalContentDbExists}","LocalContentDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":195,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"12d52710-f77d-4a10-8dde-05169b235959"}
{"@t":"2020-03-13T15:17:47.7467623Z","@mt":"Creating the media store, localMediaDbExists? {LocalMediaDbExists}","LocalMediaDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":195,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"12d52710-f77d-4a10-8dde-05169b235959"}
{"@t":"2020-03-13T15:17:48.1222988Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Loading content from local cache file","TimingId":"81e27d1","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":195,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"12d52710-f77d-4a10-8dde-05169b235959"}
{"@t":"2020-03-13T15:17:48.1452778Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":23,"TimingId":"81e27d1","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":195,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"12d52710-f77d-4a10-8dde-05169b235959"}
{"@t":"2020-03-13T15:17:48.1522861Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Loading media from local cache file","TimingId":"885e9c1","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":195,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"12d52710-f77d-4a10-8dde-05169b235959"}
{"@t":"2020-03-13T15:17:48.1532858Z","@mt":"Tried to load media from the local cache file but it was empty.","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":195,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"12d52710-f77d-4a10-8dde-05169b235959"}
{"@t":"2020-03-13T15:17:48.1532858Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":0,"TimingId":"885e9c1","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":195,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"12d52710-f77d-4a10-8dde-05169b235959"}
{"@t":"2020-03-13T15:17:48.1532858Z","@mt":"Loading media from local db raised warnings, will reload from database.","@l":"Warning","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":195,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"WARN ","HttpRequestNumber":1,"HttpRequestId":"12d52710-f77d-4a10-8dde-05169b235959"}
{"@t":"2020-03-13T15:17:48.1542767Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Loading media from database","TimingId":"0158140","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":195,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"12d52710-f77d-4a10-8dde-05169b235959"}
{"@t":"2020-03-13T15:17:48.3953576Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":240,"TimingId":"0158140","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":195,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"12d52710-f77d-4a10-8dde-05169b235959"}
{"@t":"2020-03-13T15:17:48.4503408Z","@mt":"Profiler is VoidProfiler, not profiling (must run debug mode to profile).","SourceContext":"Umbraco.Web.Logging.WebProfilerComponent","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":195,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"12d52710-f77d-4a10-8dde-05169b235959"}
{"@t":"2020-03-13T15:17:48.5993040Z","@mt":"Initializing Umbraco internal event handlers for cache refreshing.","SourceContext":"Umbraco.Web.Cache.DistributedCacheBinderComponent","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":195,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"12d52710-f77d-4a10-8dde-05169b235959"}
{"@t":"2020-03-13T15:17:48.6857973Z","@mt":"Adding examine event handlers for {RegisteredIndexers} index providers.","RegisteredIndexers":3,"SourceContext":"Umbraco.Web.Search.ExamineComponent","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":195,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"12d52710-f77d-4a10-8dde-05169b235959"}
{"@t":"2020-03-13T15:17:48.7117787Z","@mt":"Starting initialize async background thread.","SourceContext":"Umbraco.Web.Search.BackgroundIndexRebuilder","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":195,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"12d52710-f77d-4a10-8dde-05169b235959"}
{"@t":"2020-03-13T15:17:48.7127799Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Booted.","Duration":2003,"TimingId":"02f7f27","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":195,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"12d52710-f77d-4a10-8dde-05169b235959"}
{"@t":"2020-03-13T15:17:49.6332943Z","@mt":"New url {Url} detected, re-discovering application url.","Url":"http://localhost/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":202,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"bebcd98b-e8c5-49dd-8ad4-d2871a929036"}
{"@t":"2020-03-13T15:17:49.6332943Z","@mt":"ApplicationUrl: {UmbracoAppUrl} (UmbracoModule request)","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":202,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"bebcd98b-e8c5-49dd-8ad4-d2871a929036"}
{"@t":"2020-03-13T15:20:51.9306605Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":180,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T15:21:01.9839786Z","@mt":"Scheduled health check results:","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Folder & File Permissions","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Folder & File Permissions","HealthCheckResult":"Success","HealthCheckMessage":"All folders have the correct permissions set.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Folder & File Permissions","HealthCheckResult":"Success","HealthCheckMessage":"All files have the correct permissions set.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"SMTP Settings","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"WARN "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"SMTP Settings","HealthCheckResult":"Error","HealthCheckMessage":"In the Web.config file system.net/mailsettings section, the host is not configured.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Macro errors","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"WARN "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Macro errors","HealthCheckResult":"Error","HealthCheckMessage":"MacroErrors are set to 'throw' which will prevent some or all pages in your site from loading completely if there are any errors in macros. Rectifying this will set the value to 'inline'.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Notification Email Settings","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"WARN "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Notification Email Settings","HealthCheckResult":"Error","HealthCheckMessage":"Notification email is still set to the default value of <strong>your@email.here</strong>.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Try Skip IIS Custom Errors","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Try Skip IIS Custom Errors","HealthCheckResult":"Success","HealthCheckMessage":"Try Skip IIS Custom Errors is set to 'true' and you're using IIS version '10.0'.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Custom Errors","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Custom Errors","HealthCheckResult":"Success","HealthCheckMessage":"Custom errors are set to 'RemoteOnly'.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Trace Mode","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Trace Mode","HealthCheckResult":"Success","HealthCheckMessage":"Trace mode is disabled.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Debug Compilation Mode","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Debug Compilation Mode","HealthCheckResult":"Success","HealthCheckMessage":"Debug compilation mode is disabled.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Cross-site scripting Protection (X-XSS-Protection header)","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"WARN "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Cross-site scripting Protection (X-XSS-Protection header)","HealthCheckResult":"Error","HealthCheckMessage":"Error pinging the URL http://localhost/umbraco - 'Unable to connect to the remote server'","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Cookie hijacking and protocol downgrade attacks Protection (Strict-Transport-Security Header (HSTS))","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"WARN "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Cookie hijacking and protocol downgrade attacks Protection (Strict-Transport-Security Header (HSTS))","HealthCheckResult":"Error","HealthCheckMessage":"Error pinging the URL http://localhost/umbraco - 'Unable to connect to the remote server'","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Content/MIME Sniffing Protection","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"WARN "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Content/MIME Sniffing Protection","HealthCheckResult":"Error","HealthCheckMessage":"Error pinging the URL http://localhost/umbraco - 'Unable to connect to the remote server'","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Excessive Headers","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"WARN "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Excessive Headers","HealthCheckResult":"Warning","HealthCheckMessage":"[httpsCheckInvalidUrl]","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Click-Jacking Protection","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"WARN "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Click-Jacking Protection","HealthCheckResult":"Error","HealthCheckMessage":"Error pinging the URL http://localhost/umbraco - 'Unable to connect to the remote server'","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"HTTPS Configuration","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"WARN "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"HTTPS Configuration","HealthCheckResult":"Error","HealthCheckMessage":"You are currently not viewing the site using the HTTPS scheme.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"HTTPS Configuration","HealthCheckResult":"Info","HealthCheckMessage":"The appSetting 'Umbraco.Core.UseHttps' is set to 'false' in your web.config file. Once you access this site using the HTTPS scheme, that should be set to 'true'.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:21:01.9849781Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"HTTPS Configuration","HealthCheckResult":"Error","HealthCheckMessage":"Error pinging the URL https://localhost/umbraco - 'Unable to connect to the remote server'","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":173,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"INFO "}
{"@t":"2020-03-13T15:25:53.9458950Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":62,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T15:30:55.9607201Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":101,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T15:35:57.9746070Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":170,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T15:40:59.9876580Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":15,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T15:46:02.0021836Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":73,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T15:51:04.0156204Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":140,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T15:56:06.0214016Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":143,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T16:01:08.0330530Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":25,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T16:06:10.0518398Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":97,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T16:11:12.0645236Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":203,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T16:16:14.0818119Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":100,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T16:21:16.0956418Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":131,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T16:26:18.1159511Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":69,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T16:31:20.1327798Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":197,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T16:36:22.1501173Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":161,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T16:41:24.1675864Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":111,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T16:46:26.1843905Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":40,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T16:51:28.1909183Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":168,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T16:56:30.2075825Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":176,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T17:01:32.2255862Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":204,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T17:06:34.2379341Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":204,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T17:11:36.2527809Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":90,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T17:16:38.2674972Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
{"@t":"2020-03-13T17:21:40.2949032Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":5548,"ProcessName":"iisexpress","ThreadId":147,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"MO-PC","Log4NetLevel":"ERROR"}
